build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "project/zephyr-blink"
    - PLATFORMIO_PROJECT_DIR: "project/arduino-blink"
    - PLATFORMIO_PROJECT_DIR: "project/libopencm3-blink"
    - PLATFORMIO_PROJECT_DIR: "project/stm32cube-ll-blink"
    - PLATFORMIO_PROJECT_DIR: "project/stm32cube-hal-blink"
install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python36\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/OS-Q/S03/archive/master.zip
  - cmd: platformio platform install https://github.com/OS-Q/P01.git

test_script:
  - cmd: platformio run -s -d %PLATFORMIO_PROJECT_DIR%
